import type { TemplateDefinition } from './types'
import type {
  ProductRoadmapData,
  StrategyData,
  Strategy6Data,
  ProcessData,
  TableData,
  AgendaData,
  ComparisonData,
  Comparison2Data,
  Comparison5Data,
  Comparison6Data,
  Comparison7Data,
  Comparison8Data,
  ManufacturingData,
  ValueChainData,
  ValueChain3Data,
  ValueChain4Data,
  ValueChain5Data,
  CircleData,
  PieData,
} from './types'

export const TEMPLATES: TemplateDefinition[] = [
  {
    type: 'roadmap',
    label: 'roadmap',
    description: 'Timeline horizontale avec jalons numérotés positionnés alternativement au-dessus et en-dessous de la ligne.',
    category: 'Roadmaps',
    defaultData: {
      type: 'roadmap',
      milestones: [
        { title: 'Milestone 1', subtitle: 'Description' },
        { title: 'Milestone 2', subtitle: 'Description', value: 'STEP 2' },
        { title: 'Milestone 3', subtitle: 'Description', value: 'STEP 3' },
        { title: 'Milestone 4', subtitle: 'Description' },
      ],
      startLabel: 'START',
      finishLabel: 'FINISH',
    },
  },
  {
    type: 'roadmap2',
    label: 'roadmap2',
    description: 'Timeline verticale avec phases colorées (Phase One, Two, Three) et jalons par années.',
    category: 'Roadmaps',
    defaultData: {
      type: 'roadmap',
      progress: '2024',
      lanes: [
        { label: 'Phase One', color: '#23255a' },
        { label: 'Phase Two', color: '#2d62ed' },
        { label: 'Phase Three', color: '#ff4a2b' },
      ],
      milestones: [
        { title: 'Initiate', subtitle: 'Project kickoff', date: '2022', lane: 'Phase One' },
        { title: 'Plan', subtitle: 'Detailed design', date: '2023', lane: 'Phase One' },
        { title: 'Develop', subtitle: 'Core features', date: '2024', lane: 'Phase Two' },
        { title: 'Test', subtitle: 'QA & validation', date: '2025', lane: 'Phase Two' },
        { title: 'Deliver', subtitle: 'Production release', date: '2026', lane: 'Phase Three' },
      ],
    },
  },
  {
    type: 'roadmap3',
    label: 'roadmap3',
    description: 'Schéma en serpentin reliant 10 années consécutives avec jalons ancrés.',
    category: 'Roadmaps',
    defaultData: {
      type: 'roadmap',
      lanes: [
        { label: 'Research', color: '#23255a' },
        { label: 'Launch', color: '#2d62ed' },
      ],
      quarters: [
        { label: '2019' }, { label: '2020' }, { label: '2021' }, { label: '2022' },
        { label: '2023' }, { label: '2024' }, { label: '2025' }, { label: '2026' },
        { label: '2027' }, { label: '2028' },
      ],
      milestones: [
        { title: 'Research', subtitle: 'Market analysis', date: '2021', lane: 'Research' },
        { title: 'Launch', subtitle: 'Go to market', date: '2026', lane: 'Launch' },
      ],
    },
  },
  {
    type: 'roadmap4',
    label: 'roadmap4',
    description: 'Timeline découpée en 5 trimestres (Q1 à Q5) avec cartes de jalons.',
    category: 'Roadmaps',
    defaultData: {
      type: 'roadmap',
      quarters: [
        { label: 'Q1', year: '2026' },
        { label: 'Q2', year: '2026' },
        { label: 'Q3', year: '2026' },
        { label: 'Q4', year: '2026' },
        { label: 'Q5', year: '2026' },
      ],
      milestones: [
        { title: 'Alpha Release', subtitle: 'Internal testing', quarter: 'Q1' },
        { title: 'Beta Launch', subtitle: 'Private preview', quarter: 'Q2' },
        { title: 'RC1', subtitle: 'Stabilization', quarter: 'Q3' },
        { title: 'RC2', subtitle: 'Hardening', quarter: 'Q4' },
        { title: 'GA Release', subtitle: 'General availability', quarter: 'Q5' },
      ],
    },
  },
  {
    type: 'roadmap4b',
    label: 'roadmap4b',
    description: 'Serpentin à 4 virages de forme FIXE : le départ et l\'arrivée sont ancrés, et les jalons ne font que diviser la forme en portions de longueurs variables (la forme générale ne bouge jamais).',
    category: 'Roadmaps',
    defaultData: {
      type: 'roadmap',
      quarters: [
        { label: 'Q1', year: '2026' },
        { label: 'Q2', year: '2026' },
        { label: 'Q3', year: '2026' },
        { label: 'Q4', year: '2026' },
        { label: 'Q5', year: '2026' },
      ],
      milestones: [
        { title: 'Milestone 01', subtitle: 'MIGSO-PCUBED content and words to\nbe added here as required' },
        { title: 'Milestone 02', subtitle: 'MIGSO-PCUBED content and words to\nbe added here as required' },
        { title: 'Milestone 03', subtitle: 'MIGSO-PCUBED content and words to\nbe added here as required' },
        { title: 'Milestone 04', subtitle: 'MIGSO-PCUBED content and words to\nbe added here as required' },
        { title: 'Milestone 05', subtitle: 'MIGSO-PCUBED content and words to\nbe added here as required' },
      ],
    },
  },
  {
    type: 'roadmap5',
    label: 'roadmap5',
    description: 'Présentation sous forme de cartes décalées en escalier avec dates clés.',
    category: 'Roadmaps',
    defaultData: {
      type: 'roadmap',
      startLabel: 'START',
      progress: '2020',
      quarters: [
        { label: '2019' },
        { label: '2020' },
        { label: '2021' },
        { label: '2022' },
      ],
      milestones: [
        { title: 'Milestone 01', subtitle: 'MIGSO-PCUBED content and words to\nbe added here as required', color: '#4cbfa0' },
        { title: 'Milestone 02', subtitle: 'MIGSO-PCUBED content and words to\nbe added here as required', date: '2019', color: '#23255a' },
        { title: 'Milestone 03', subtitle: 'MIGSO-PCUBED content and words to\nbe added here as required', date: '2020', color: '#23255a' },
        { title: 'Milestone 04', subtitle: 'MIGSO-PCUBED content and words to\nbe added here as required', date: '2021', color: '#2d62ed' },
      ],
    },
  },
  {
    type: 'roadmap6',
    label: 'roadmap6',
    description: 'Timeline de jalons hebdomadaires étalés sur plusieurs années.',
    category: 'Roadmaps',
    defaultData: {
      type: 'roadmap',
      quarters: [
        { label: '2024' },
        { label: '2025' },
        { label: '2026' },
      ],
      milestones: [
        { title: 'Setup env', subtitle: 'Infrastructure', date: '2024' },
        { title: 'Login page', subtitle: 'Auth module', date: '2024' },
        { title: 'Dashboard', subtitle: 'Main UI', date: '2025' },
        { title: 'API layer', subtitle: 'Backend REST', date: '2025' },
        { title: 'DB schema', subtitle: 'Data model', date: '2025' },
        { title: 'Tests', subtitle: 'QA coverage', date: '2026' },
        { title: 'Deploy CI', subtitle: 'Pipeline setup', date: '2026' },
        { title: 'Launch', subtitle: 'Go live', date: '2026' },
      ],
    },
  },
  {
    type: 'roadmap7',
    label: 'roadmap7',
    description: 'Timeline verticale avec bulles de jalons numérotées, connecteurs triangulaires et descriptions.',
    category: 'Roadmaps',
    defaultData: {
      type: 'roadmap',
      milestones: [
        { title: 'Cadrage Initial', subtitle: 'Définition du périmètre et objectifs', date: '2023', value: '01' },
        { title: 'Développement', subtitle: 'Implémentation des modules coeur', date: '2024', value: '02' },
        { title: 'Déploiement', subtitle: 'Lancement et mise en production', date: '2025', value: '03' },
      ],
    },
  },
  {
    type: 'roadmap8',
    label: 'roadmap8',
    description: 'Timeline à jalons décalés avec sous-titres de périmètre.',
    category: 'Roadmaps',
    defaultData: {
      type: 'roadmap',
      milestones: [
        { title: 'Research', subtitle: 'Competitive analysis', date: '2023' },
        { title: 'Plan', subtitle: 'Scope definition', date: '2024' },
        { title: 'Execute', subtitle: 'Development sprints', date: '2025' },
        { title: 'Review', subtitle: 'Quality assurance', date: '2026' },
      ],
    },
  },
  {
    type: 'roadmap9',
    label: 'roadmap9',
    description: 'Deux niveaux de jalons (haut et bas) reliés à un axe central.',
    category: 'Roadmaps',
    defaultData: {
      type: 'roadmap',
      milestones: [
        { title: 'Research' },
        { title: 'Design' },
        { title: 'Development' },
        { title: 'Testing' },
        { title: 'Deploy' },
        { title: 'Iterate' },
      ],
    },
  },
  {
    type: 'roadmap10',
    label: 'roadmap10',
    description: 'Cartes de jalons avec affichage en grands caractères pour les mois.',
    category: 'Roadmaps',
    defaultData: {
      type: 'roadmap',
      milestones: [
        { title: 'Ideation', subtitle: 'Brainstorm concepts', date: 'JAN' },
        { title: 'Validation', subtitle: 'Customer interviews', date: 'MAR' },
        { title: 'MVP Build', subtitle: 'Core features only', date: 'JUN' },
        { title: 'Launch', subtitle: 'Public release', date: 'SEP' },
      ],
    },
  },
  {
    type: 'roadmap11',
    label: 'roadmap11',
    description: 'Liste verticale de jalons mensuels avec indicateurs de progression.',
    category: 'Roadmaps',
    defaultData: {
      type: 'roadmap',
      milestones: [
        { title: 'Initiate', subtitle: 'Project charter & team assembly', date: 'JANUARY' },
        { title: 'Plan', subtitle: 'Timeline, budget & resource allocation', date: 'FEBRUARY' },
        { title: 'Execute', subtitle: 'Development & integration phases', date: 'MARCH' },
        { title: 'Monitor', subtitle: 'KPI tracking & risk management', date: 'APRIL' },
        { title: 'Close', subtitle: 'Final delivery & retrospective', date: 'MAY' },
      ],
    },
  },
  {
    type: 'roadmap12',
    label: 'roadmap12',
    description: 'Timeline sous forme de chemin par étapes numérotées.',
    category: 'Roadmaps',
    defaultData: {
      type: 'roadmap',
      milestones: [
        { title: 'Analyze', subtitle: 'Gather requirements' },
        { title: 'Design', subtitle: 'Create blueprint' },
        { title: 'Implement', subtitle: 'Build solution' },
        { title: 'Verify', subtitle: 'Test & validate' },
      ],
    },
  },
  {
    type: 'roadmap13',
    label: 'roadmap13',
    description: 'Grille de colonnes hebdomadaires (Week 1 à Week 8).',
    category: 'Roadmaps',
    defaultData: {
      type: 'roadmap',
      milestones: [
        { title: 'Kickoff', subtitle: 'Team alignment', date: 'Week 1' },
        { title: 'Research', subtitle: 'User interviews', date: 'Week 2' },
        { title: 'Wireframes', subtitle: 'Low-fidelity mockups', date: 'Week 3' },
        { title: 'Prototype', subtitle: 'Interactive demo', date: 'Week 4' },
        { title: 'Dev Sprint 1', subtitle: 'Core features', date: 'Week 5' },
        { title: 'Dev Sprint 2', subtitle: 'Polish & QA', date: 'Week 6' },
        { title: 'UAT', subtitle: 'User validation', date: 'Week 7' },
        { title: 'Release', subtitle: 'Production deploy', date: 'Week 8' },
      ],
    },
  },
  {
    type: 'roadmap14',
    label: 'roadmap14',
    description: 'Timeline prospective s\'étalant sur plusieurs années.',
    category: 'Roadmaps',
    defaultData: {
      type: 'roadmap',
      milestones: [
        { title: 'Foundation', subtitle: 'Core platform', date: '2023' },
        { title: 'Growth', subtitle: 'Feature expansion', date: '2024' },
        { title: 'Scale', subtitle: 'Infrastructure upgrade', date: '2025' },
        { title: 'Optimize', subtitle: 'Performance & UX', date: '2026' },
      ],
    },
  },
  {
    type: 'roadmap15',
    label: 'roadmap15',
    description: 'Blocs de jalons trimestriels avec barre de progression globale.',
    category: 'Roadmaps',
    defaultData: {
      type: 'roadmap',
      milestones: [
        { title: 'Research', subtitle: 'Market study', date: 'Q1 2025' },
        { title: 'Prototype', subtitle: 'Proof of concept', date: 'Q2 2025' },
        { title: 'Development', subtitle: 'Build phase', date: 'Q3 2025' },
        { title: 'Testing', subtitle: 'QA cycle', date: 'Q4 2025' },
        { title: 'Launch', subtitle: 'Go live', date: 'Q1 2026' },
      ],
      startLabel: 'START',
      finishLabel: 'FINISH',
    },
  },
  {
    type: 'roadmap16',
    label: 'roadmap16',
    description: 'Parcours sinueux reliant les étapes d\'idéation à la livraison.',
    category: 'Roadmaps',
    defaultData: {
      type: 'roadmap',
      milestones: [
        { title: 'Concept', subtitle: 'Idea validation', date: '2023' },
        { title: 'Design', subtitle: 'UX & architecture', date: '2024' },
        { title: 'Develop', subtitle: 'Core modules', date: '2025' },
        { title: 'Test', subtitle: 'QA & UAT', date: '2026' },
        { title: 'Deliver', subtitle: 'Production release', date: '2027' },
      ],
      startLabel: 'START',
      finishLabel: 'FINISH',
    },
  },
  {
    type: 'productRoadmap',
    label: 'productRoadmap',
    description: 'Grille trimestrielle (Q1-Q4) croisée avec 4 pôles (Dev, Product, UX, QA).',
    category: 'Product Roadmaps',
    defaultData: {
      type: 'productRoadmap',
      quarters: [
        { label: 'Q1', year: '2026' },
        { label: 'Q2', year: '2026' },
        { label: 'Q3', year: '2026' },
        { label: 'Q4', year: '2026' },
      ],
      lanes: [
        { label: 'Development' },
        { label: 'Product' },
        { label: 'UX' },
        { label: 'QA' },
      ],
      milestones: [
        { title: 'Alpha', quarter: 'Q1', lane: 'Development' },
        { title: 'Beta', quarter: 'Q2', lane: 'Product' },
        { title: 'RC1', quarter: 'Q3', lane: 'QA' },
        { title: 'Launch', quarter: 'Q4', lane: 'Development' },
      ],
    },
  },
  {
    type: 'productRoadmap2',
    label: 'productRoadmap2',
    description: 'Grille trimestrielle avec bandes d\'équipes et badges de fonctionnalités.',
    category: 'Product Roadmaps',
    defaultData: {
      type: 'productRoadmap2',
      quarters: [
        { label: 'Q1', year: '2026' },
        { label: 'Q2', year: '2026' },
        { label: 'Q3', year: '2026' },
        { label: 'Q4', year: '2026' },
      ],
      lanes: [
        { label: 'Development' },
        { label: 'Product' },
        { label: 'UX' },
        { label: 'QA' },
      ],
      milestones: [
        { title: 'Alpha', quarter: 'Q1', lane: 'Development' },
        { title: 'Beta', quarter: 'Q2', lane: 'Product' },
        { title: 'RC1', quarter: 'Q3', lane: 'QA' },
        { title: 'Launch', quarter: 'Q4', lane: 'Development' },
      ],
    },
  },
  {
    type: 'productRoadmap3',
    label: 'productRoadmap3',
    description: 'Grille trimestrielle avec cartes détaillées contenant titres et sous-titres.',
    category: 'Product Roadmaps',
    defaultData: {
      type: 'productRoadmap3',
      quarters: [
        { label: 'Q1', year: '2026' },
        { label: 'Q2', year: '2026' },
        { label: 'Q3', year: '2026' },
        { label: 'Q4', year: '2026' },
      ],
      lanes: [
        { label: 'Development' },
        { label: 'Product' },
        { label: 'UX' },
        { label: 'QA' },
      ],
      milestones: [
        { title: 'Alpha', subtitle: 'First working prototype', quarter: 'Q1', lane: 'Development' },
        { title: 'Beta', subtitle: 'Feature complete', quarter: 'Q2', lane: 'Product' },
        { title: 'RC1', subtitle: 'Release candidate', quarter: 'Q3', lane: 'QA' },
        { title: 'Launch', subtitle: 'Public release', quarter: 'Q4', lane: 'Development' },
      ],
    },
  },
  {
    type: 'productRoadmap4',
    label: 'productRoadmap4',
    description: 'Matrice centrée sur les phases de recherche, prototypage et mise sur le marché.',
    category: 'Product Roadmaps',
    defaultData: {
      type: 'productRoadmap4',
      quarters: [
        { label: 'Q1', year: '2026' },
        { label: 'Q2', year: '2026' },
        { label: 'Q3', year: '2026' },
        { label: 'Q4', year: '2026' },
      ],
      lanes: [
        { label: 'Development' },
        { label: 'Product' },
        { label: 'UX' },
        { label: 'QA' },
      ],
      milestones: [
        { title: 'Discovery', subtitle: 'Research & ideation', quarter: 'Q1', lane: 'Product' },
        { title: 'Prototype', subtitle: 'Build MVP', quarter: 'Q2', lane: 'Development' },
        { title: 'Testing', subtitle: 'User validation', quarter: 'Q3', lane: 'QA' },
        { title: 'Launch', subtitle: 'Go to market', quarter: 'Q4', lane: 'Development' },
      ],
    },
  },
  {
    type: 'productRoadmap5',
    label: 'productRoadmap5',
    description: 'Vue en tableau des livrables clés par trimestre et pôle métier.',
    category: 'Product Roadmaps',
    defaultData: {
      type: 'productRoadmap5',
      quarters: [
        { label: 'Q1', year: '2026' },
        { label: 'Q2', year: '2026' },
        { label: 'Q3', year: '2026' },
        { label: 'Q4', year: '2026' },
      ],
      lanes: [
        { label: 'Development' },
        { label: 'Product' },
        { label: 'UX' },
        { label: 'QA' },
      ],
      milestones: [
        { title: 'Alpha', subtitle: 'First working prototype', quarter: 'Q1', lane: 'Development' },
        { title: 'Beta', subtitle: 'Feature complete', quarter: 'Q2', lane: 'Product' },
        { title: 'RC1', subtitle: 'Release candidate', quarter: 'Q3', lane: 'QA' },
        { title: 'Launch', subtitle: 'Public release', quarter: 'Q4', lane: 'Development' },
      ],
    },
  },
  {
    type: 'productRoadmap6',
    label: 'productRoadmap6',
    description: 'Vue condensée des fonctionnalités à livrer par trimestre.',
    category: 'Product Roadmaps',
    defaultData: {
      type: 'productRoadmap6',
      quarters: [
        { label: 'Q1', year: '2026' },
        { label: 'Q2', year: '2026' },
        { label: 'Q3', year: '2026' },
        { label: 'Q4', year: '2026' },
      ],
      lanes: [
        { label: 'Development' },
        { label: 'Product' },
        { label: 'UX' },
        { label: 'QA' },
      ],
      milestones: [
        { title: 'Alpha', subtitle: 'First working prototype', quarter: 'Q1', lane: 'Development' },
        { title: 'Beta', subtitle: 'Feature complete', quarter: 'Q2', lane: 'Product' },
        { title: 'RC1', subtitle: 'Release candidate', quarter: 'Q3', lane: 'QA' },
        { title: 'Launch', subtitle: 'Public release', quarter: 'Q4', lane: 'Development' },
      ],
    },
  },
  {
    type: 'strategy',
    label: 'strategy',
    description: 'Alignement horizontal de 5 blocs représentant les axes stratégiques.',
    category: 'Strategy',
    defaultData: {
      type: 'strategy',
      blocks: [
        { number: '01', title: 'Vision', subtitle: 'Define the vision' },
        { number: '02', title: 'Goals', subtitle: 'Set clear goals' },
        { number: '03', title: 'Execution', subtitle: 'Execute the plan' },
        { number: '04', title: 'Review', subtitle: 'Measure results' },
        { number: '05', title: 'Iterate', subtitle: 'Improve continuously' },
      ],
    },
  },
  {
    type: 'strategy2',
    label: 'strategy2',
    description: 'Pyramide à 5 niveaux (Vision, Mission, Objectifs, Initiatives, Fondations).',
    category: 'Strategy',
    defaultData: {
      type: 'strategy2',
      blocks: [
        { number: '01', title: 'Vision', subtitle: 'North Star direction' },
        { number: '02', title: 'Mission', subtitle: 'What we do & why' },
        { number: '03', title: 'Goals', subtitle: 'Measurable targets' },
        { number: '04', title: 'Initiatives', subtitle: 'Key programs' },
        { number: '05', title: 'Foundation', subtitle: 'Core capabilities' },
      ],
    },
  },
  {
    type: 'strategy3',
    label: 'strategy3',
    description: 'Disposition en étoile autour d\'un sujet central avec 6 rayons.',
    category: 'Strategy',
    defaultData: {
      type: 'strategy3',
      blocks: [
        { number: '01', title: 'Customer', subtitle: 'Client experience' },
        { number: '02', title: 'Innovation', subtitle: 'R&D and tech' },
        { number: '03', title: 'Operations', subtitle: 'Process excellence' },
        { number: '04', title: 'Finance', subtitle: 'Sustainable growth' },
        { number: '05', title: 'People', subtitle: 'Talent & culture' },
        { number: '06', title: 'Brand', subtitle: 'Market positioning' },
      ],
    },
  },
  {
    type: 'strategy4',
    label: 'strategy4',
    description: 'Disposition en 3 colonnes verticales avec 6 blocs stratégiques.',
    category: 'Strategy',
    defaultData: {
      type: 'strategy4',
      blocks: [
        { number: '01', title: 'Market Expansion', subtitle: 'New regions' },
        { number: '02', title: 'Product Excellence', subtitle: 'Quality first' },
        { number: '03', title: 'Customer Success', subtitle: 'Retention focus' },
        { number: '04', title: 'Talent Growth', subtitle: 'Hire & develop' },
        { number: '05', title: 'Digital Transform', subtitle: 'Tech upgrade' },
        { number: '06', title: 'Sustainability', subtitle: 'ESG goals' },
      ],
    },
  },
  {
    type: 'strategy5',
    label: 'strategy5',
    description: 'Timeline stratégique découpée par objectifs trimestriels.',
    category: 'Strategy',
    defaultData: {
      type: 'strategy5',
      blocks: [
        { number: '01', title: 'Market Analysis', subtitle: 'Q1 Focus' },
        { number: '02', title: 'Product Redesign', subtitle: 'Q2 Focus' },
        { number: '03', title: 'Go-to-Market', subtitle: 'Q3 Focus' },
        { number: '04', title: 'Scale Operations', subtitle: 'Q4 Focus' },
        { number: '05', title: 'Global Expansion', subtitle: 'Next Year' },
      ],
    },
  },
  {
    type: 'process',
    label: 'process',
    description: 'Flux séquentiel de 4 étapes avec résultat final (Outcome).',
    category: 'Process',
    defaultData: {
      type: 'process',
      steps: [
        { number: 1, title: 'Analyze', subtitle: 'Understand the problem' },
        { number: 2, title: 'Design', subtitle: 'Create solution' },
        { number: 3, title: 'Implement', subtitle: 'Build the solution' },
        { number: 4, title: 'Validate', subtitle: 'Test and verify' },
      ],
      outcome: 'Success',
    },
  },
  {
    type: 'process2',
    label: 'process2',
    description: 'Étapes interconnectées par des flèches directionnelles.',
    category: 'Process',
    defaultData: {
      type: 'process2',
      steps: [
        { number: 1, title: 'Research', subtitle: 'Gather data' },
        { number: 2, title: 'Design', subtitle: 'Create blueprint' },
        { number: 3, title: 'Build', subtitle: 'Develop solution' },
        { number: 4, title: 'Launch', subtitle: 'Go live' },
      ],
      outcome: 'Success',
    },
  },
  {
    type: 'process4',
    label: 'process4',
    description: 'Cartes de phases avec numéro, titre et sous-titre.',
    category: 'Process',
    defaultData: {
      type: 'process4',
      steps: [
        { number: 1, title: 'Plan', subtitle: 'Define scope & objectives' },
        { number: 2, title: 'Execute', subtitle: 'Implement the action plan' },
        { number: 3, title: 'Monitor', subtitle: 'Track progress & KPIs' },
        { number: 4, title: 'Close', subtitle: 'Finalize & deliver' },
      ],
      outcome: 'Delivered',
    },
  },
  {
    type: 'process5',
    label: 'process5',
    description: 'Flux vertical étape par étape de l\'idéation au release.',
    category: 'Process',
    defaultData: {
      type: 'process5',
      steps: [
        { number: 1, title: 'Ideation', subtitle: 'Brainstorm concepts' },
        { number: 2, title: 'Prototyping', subtitle: 'Build MVP' },
        { number: 3, title: 'Testing', subtitle: 'Validate with users' },
        { number: 4, title: 'Iteration', subtitle: 'Refine & improve' },
        { number: 5, title: 'Release', subtitle: 'Ship to production' },
      ],
      outcome: 'Launched',
    },
  },
  {
    type: 'puzzle',
    label: 'puzzle',
    description: 'Puzzle 2x2 carré (Slide 180) à 4 pièces avec pignons extérieurs et cartes descriptives reliées.',
    category: 'Puzzles',
    defaultData: {
      type: 'puzzle',
      pieces: [
        { number: '1', title: 'Identify', subtitle: 'MIGSO-PCUBED\ncontent and words to\nbe added here as\nrequired', color: '#2c2b64' },
        { number: '2', title: 'Innovation', subtitle: 'MIGSO-PCUBED\ncontent and words to\nbe added here as\nrequired', color: '#3466ce' },
        { number: '3', title: 'Management', subtitle: 'MIGSO-PCUBED\ncontent and words to\nbe added here as\nrequired', color: '#ff4d30' },
        { number: '4', title: 'Improve', subtitle: 'MIGSO-PCUBED\ncontent and words to\nbe added here as\nrequired', color: '#ffb703' },
      ],
    },
  },
  {
    type: 'puzzle2',
    label: 'puzzle2',
    description: 'Assemblage en losange de 4 pièces puzzle imbriquées avec points et textes.',
    category: 'Puzzles',
    defaultData: {
      type: 'puzzle',
      pieces: [
        { number: 1, title: 'Identify', subtitle: 'MIGSO-PCUBED content and words to be added here as required', color: '#2c2b64', icon: 'clock' },
        { number: 2, title: 'Improve', subtitle: 'MIGSO-PCUBED content and words to be added here as required', color: '#3466ce', icon: 'gear' },
        { number: 3, title: 'Innovation', subtitle: 'MIGSO-PCUBED content and words to be added here as required', color: '#ff5338', icon: 'briefcase' },
        { number: 4, title: 'Management', subtitle: 'MIGSO-PCUBED content and words to be added here as required', color: '#ffc000', icon: 'people' },
      ],
    },
  },
  {
    type: 'puzzle3',
    label: 'puzzle3',
    description: 'Disposition verticale de pièces de puzzle imbriquées.',
    category: 'Puzzles',
    defaultData: {
      type: 'puzzle',
      pieces: [
        { number: 1, title: 'Analysis', subtitle: 'Detailed research', color: '#1a2249' },
        { number: 2, title: 'Design', subtitle: 'System architecture', color: '#2b63d9' },
        { number: 3, title: 'Build', subtitle: 'Implementation phase', color: '#ff5338' },
        { number: 4, title: 'Deploy', subtitle: 'Production release', color: '#ffb100' },
      ],
    },
  },
  {
    type: 'puzzle4',
    label: 'puzzle4',
    description: 'Puzzle 2x2 carré (Slide 180) à 4 pièces avec pignons extérieurs et cartes descriptives reliées.',
    category: 'Puzzles',
    defaultData: {
      type: 'puzzle',
      pieces: [
        { number: '1', title: 'Identify', subtitle: 'MIGSO-PCUBED\ncontent and words to\nbe added here as\nrequired', color: '#2c2b64' },
        { number: '2', title: 'Innovation', subtitle: 'MIGSO-PCUBED\ncontent and words to\nbe added here as\nrequired', color: '#3466ce' },
        { number: '3', title: 'Management', subtitle: 'MIGSO-PCUBED\ncontent and words to\nbe added here as\nrequired', color: '#ff4d30' },
        { number: '4', title: 'Improve', subtitle: 'MIGSO-PCUBED\ncontent and words to\nbe added here as\nrequired', color: '#ffb703' },
      ],
    },
  },
  {
    type: 'puzzle5',
    label: 'puzzle5',
    description: 'Hexagones horizontaux imbriqués en quinconce (A, B, C, D, E).',
    category: 'Puzzles',
    defaultData: {
      type: 'puzzle',
      pieces: [
        { number: 1, title: 'Improve', subtitle: 'MIGSO-PCUBED content and words to be added here as required', color: '#1a2249', value: 'A' },
        { number: 2, title: 'Identify', subtitle: 'MIGSO-PCUBED content and words to be added here as required', color: '#2b63d9', value: 'B' },
        { number: 3, title: 'Management', subtitle: 'MIGSO-PCUBED content and words to be added here as required', color: '#ff5338', value: 'C' },
        { number: 4, title: 'Innovation', subtitle: 'MIGSO-PCUBED content and words to be added here as required', color: '#ffb100', value: 'D' },
        { number: 5, title: 'Audience', subtitle: 'MIGSO-PCUBED content and words to be added here as required', color: '#48bb95', value: 'E' },
      ],
    },
  },
  {
    type: 'puzzle6',
    label: 'puzzle6',
    description: 'Grande pièce de puzzle filaire centrale avec 4 segments ouverts et 4 coins A, B, C, D.',
    category: 'Puzzles',
    defaultData: {
      type: 'puzzle',
      pieces: [
        { number: 1, title: 'Identify', subtitle: 'MIGSO-PCUBED content and words to be added here as required', color: '#1a2249', value: 'A' },
        { number: 2, title: 'Management', subtitle: 'MIGSO-PCUBED content and words to be added here as required', color: '#2b63d9', value: 'B' },
        { number: 3, title: 'Innovation', subtitle: 'MIGSO-PCUBED content and words to be added here as required', color: '#ff5338', value: 'C' },
        { number: 4, title: 'Improve', subtitle: 'MIGSO-PCUBED content and words to be added here as required', color: '#ffb100', value: 'D' },
      ],
    },
  },
  {
    type: 'puzzle7',
    label: 'puzzle7',
    description: 'Cadre carré aux coins arrondis creux composé de 4 quadrants puzzle imbriqués (1, 2, 3, 4).',
    category: 'Puzzles',
    defaultData: {
      type: 'puzzle',
      pieces: [
        { number: 1, title: 'Improve', subtitle: 'MIGSO-PCUBED content and words to be added here as required', color: '#1a2249' },
        { number: 2, title: 'Innovation', subtitle: 'MIGSO-PCUBED content and words to be added here as required', color: '#2b63d9' },
        { number: 3, title: 'Management', subtitle: 'MIGSO-PCUBED content and words to be added here as required', color: '#ff5338' },
        { number: 4, title: 'Identify', subtitle: 'MIGSO-PCUBED content and words to be added here as required', color: '#ffb100' },
      ],
    },
  },
  {
    type: 'funnel',
    label: 'funnel',
    description: 'Entonnoir classique à 4 niveaux (Awareness, Interest, Consideration, Purchase).',
    category: 'Funnels',
    defaultData: {
      type: 'funnel',
      levels: [
        { title: 'Awareness', percentage: 100, color: '#2c2b64' },
        { title: 'Interest', percentage: 75, color: '#3366cc' },
        { title: 'Consideration', percentage: 50, color: '#ff5338' },
        { title: 'Purchase', percentage: 25, color: '#f2cb13' },
      ],
    },
  },
  {
    type: 'funnel2',
    label: 'funnel2',
    description: 'Entonnoir couché horizontalement de la prospection au closing.',
    category: 'Funnels',
    defaultData: {
      type: 'funnel',
      levels: [
        { title: 'Leads', percentage: 100, color: '#2c2b64' },
        { title: 'MQL', percentage: 70, color: '#3366cc' },
        { title: 'SQL', percentage: 40, color: '#ff5338' },
        { title: 'Won', percentage: 20, color: '#f2cb13' },
      ],
    },
  },
  {
    type: 'funnel3',
    label: 'funnel3',
    description: 'Représentation 3D en couches empilées avec pourcentages.',
    category: 'Funnels',
    defaultData: {
      type: 'funnel',
      levels: [
        { title: 'Visitors', percentage: 100, color: '#2c2b64' },
        { title: 'Sign-ups', percentage: 60, color: '#3366cc' },
        { title: 'Active', percentage: 35, color: '#ff5338' },
        { title: 'Paying', percentage: 15, color: '#f2cb13' },
      ],
    },
  },
  {
    type: 'funnel4',
    label: 'funnel4',
    description: 'Entonnoir se séparant en deux parcours au niveau inférieur.',
    category: 'Funnels',
    defaultData: {
      type: 'funnel',
      levels: [
        { title: 'Traffic', percentage: 100, color: '#2c2b64' },
        { title: 'Engaged', percentage: 55, color: '#3366cc' },
        { title: 'Plan A', percentage: 30, color: '#ff5338' },
        { title: 'Plan B', percentage: 25, color: '#f2cb13' },
      ],
    },
  },
  {
    type: 'funnel5',
    label: 'funnel5',
    description: 'Entonnoir par segments gradués avec pourcentages de conversion.',
    category: 'Funnels',
    defaultData: {
      type: 'funnel',
      levels: [
        { title: 'Awareness', percentage: 100, color: '#2c2b64' },
        { title: 'Interest', percentage: 75, color: '#3366cc' },
        { title: 'Decision', percentage: 45, color: '#ff5338' },
        { title: 'Action', percentage: 20, color: '#f2cb13' },
      ],
    },
  },
  {
    type: 'iceberg',
    label: 'iceberg',
    description: 'Diagramme séparant les éléments émergés (visibles) et immergés (cachés).',
    category: 'Icebergs',
    defaultData: {
      type: 'iceberg',
      sections: [
        { title: 'Results', subtitle: 'Visible outcomes', isAbove: true },
        { title: 'Strategy', subtitle: 'Hidden planning', isAbove: false },
        { title: 'Culture', subtitle: 'Hidden values', isAbove: false },
        { title: 'Process', subtitle: 'Hidden foundation', isAbove: false },
      ],
    },
  },
  {
    type: 'iceberg2',
    label: 'iceberg2',
    description: 'Vue verticale des efforts et apprentissages sous la surface du succès.',
    category: 'Icebergs',
    defaultData: {
      type: 'iceberg',
      sections: [
        { title: 'Success', subtitle: 'Visible to all', isAbove: true },
        { title: 'Persistence', subtitle: 'Hidden effort', isAbove: false },
        { title: 'Sacrifice', subtitle: 'Hidden cost', isAbove: false },
        { title: 'Failure', subtitle: 'Hidden learning', isAbove: false },
      ],
    },
  },
  {
    type: 'dashboard',
    label: 'dashboard',
    description: 'Grille de 4 cartes métriques (Chiffre d\'affaires, Utilisateurs, Churn, NPS).',
    category: 'Dashboards',
    defaultData: {
      type: 'dashboard',
      metrics: [
        { label: 'Revenue', value: '$2.4M', change: '+12%', color: '#4caf50' },
        { label: 'Users', value: '48.5K', change: '+8%', color: '#2196f3' },
        { label: 'Churn', value: '2.1%', change: '-0.5%', color: '#ff9800' },
        { label: 'NPS', value: '72', change: '+5', color: '#9c27b0' },
      ],
    },
  },
  {
    type: 'dashboard2',
    label: 'dashboard2',
    description: 'Grand affichage de la métrique clé accompagné de cartes secondaires.',
    category: 'Dashboards',
    defaultData: {
      type: 'dashboard',
      metrics: [
        { label: 'MRR', value: '$842K', change: '+18%', color: '#4caf50' },
        { label: 'Trials', value: '2.4K', change: '+22%', color: '#2196f3' },
        { label: 'Churn', value: '1.8%', change: '-0.3%', color: '#ff9800' },
        { label: 'NPS', value: '81', change: '+7', color: '#9c27b0' },
      ],
    },
  },
  {
    type: 'dashboard3',
    label: 'dashboard3',
    description: 'Cartes KPI avec barres de progression et variations.',
    category: 'Dashboards',
    defaultData: {
      type: 'dashboard',
      metrics: [
        { label: 'Revenue', value: '$2.4M', change: '+12%', color: '#4caf50' },
        { label: 'Users', value: '48.5K', change: '+8%', color: '#2196f3' },
        { label: 'Sessions', value: '128K', change: '+15%', color: '#ff9800' },
        { label: 'Conversion', value: '3.2%', change: '-0.1%', color: '#9c27b0' },
      ],
    },
  },
  {
    type: 'dashboard4',
    label: 'dashboard4',
    description: 'Affichage sous forme de jauges et compteurs.',
    category: 'Dashboards',
    defaultData: {
      type: 'dashboard',
      metrics: [
        { label: 'CPU', value: '42', change: '-5', color: '#4caf50' },
        { label: 'Memory', value: '68', change: '+3', color: '#ff9800' },
        { label: 'Disk', value: '31', change: '-2', color: '#2196f3' },
        { label: 'Network', value: '56', change: '+10', color: '#9c27b0' },
      ],
    },
  },
  {
    type: 'dashboard5',
    label: 'dashboard5',
    description: 'Vue condensée des principaux indicateurs de performance.',
    category: 'Dashboards',
    defaultData: {
      type: 'dashboard',
      metrics: [
        { label: 'Revenue', value: '$42K', change: '+8%', color: '#4caf50' },
        { label: 'Orders', value: '847', change: '+12%', color: '#2196f3' },
        { label: 'AvgOrder', value: '$49', change: '+2%', color: '#9c27b0' },
        { label: 'Visitors', value: '12.4K', change: '-3%', color: '#ff9800' },
        { label: 'Bounce', value: '24%', change: '-5%', color: '#4caf50' },
        { label: 'Time', value: '4:32', change: '+8%', color: '#2196f3' },
      ],
    },
  },
  {
    type: 'table',
    label: 'table',
    description: 'Tableau de données avec en-têtes et lignes structurées.',
    category: 'Tables',
    defaultData: {
      type: 'table',
      columns: ['Column 1', 'Column 2', 'Column 3'],
      rows: [
        { label: 'Row 1', cells: ['Data A1', 'Data B1', 'Data C1'] },
        { label: 'Row 2', cells: ['Data A2', 'Data B2', 'Data C2'] },
        { label: 'Row 3', cells: ['Data A3', 'Data B3', 'Data C3'] },
      ],
    },
  },
  {
    type: 'agenda',
    label: 'agenda',
    description: 'Liste chronologique des points à traiter avec numérotation.',
    category: 'Agendas',
    defaultData: {
      type: 'agenda',
      items: [
        { number: '01', title: 'Introduction' },
        { number: '02', title: 'Project Review' },
        { number: '03', title: 'Q&A' },
        { number: '04', title: 'Next Steps' },
      ],
    },
  },
  {
    type: 'comparison',
    label: 'comparison',
    description: 'Comparaison entre 2 marques/options avec badges hexagonaux, jauges et cartes descriptives (Slide 66).',
    category: 'Comparisons',
    defaultData: {
      type: 'comparison',
      blocks: [
        {
          title: 'Brand 01',
          subtitle: 'MIGSO-PCUBED content and words to\nbe added here as required',
          value: '95%',
          icon: 'leaf',
          color: '#2c2b64',
        },
        {
          title: 'Brand 02',
          subtitle: 'MIGSO-PCUBED content and words to\nbe added here as required',
          value: '50%',
          icon: 'mobile',
          color: '#ff5338',
        },
      ],
    } as ComparisonData,
  },
  {
    type: 'brain',
    label: 'brain',
    description: 'Sujet central avec branches diffusant vers les idées secondaires.',
    category: 'Brains',
    supportsStroke: false,
    defaultData: {
      type: 'brain',
      centerLabel: 'Main Idea',
      branches: [
        { title: 'Branch 1', subtitle: 'Description' },
        { title: 'Branch 2', subtitle: 'Description' },
        { title: 'Branch 3', subtitle: 'Description' },
        { title: 'Branch 4', subtitle: 'Description' },
      ],
    },
  },
  {
    type: 'brain2',
    label: 'brain2',
    description: 'Sujet central avec branches réparties à gauche et à droite.',
    category: 'Brains',
    supportsStroke: false,
    defaultData: {
      type: 'brain',
      centerLabel: 'Core Idea',
      branches: [
        { title: 'Left Branch 1', subtitle: 'Logical side' },
        { title: 'Left Branch 2', subtitle: 'Data analysis' },
        { title: 'Right Branch 1', subtitle: 'Creative side' },
        { title: 'Right Branch 2', subtitle: 'Design thinking' },
        { title: 'Right Branch 3', subtitle: 'Storytelling' },
      ],
    },
  },
  {
    type: 'brain3',
    label: 'brain3',
    description: 'Réseau d\'idées interconnectées autour d\'un noyau.',
    category: 'Brains',
    supportsStroke: false,
    defaultData: {
      type: 'brain',
      centerLabel: 'Central Topic',
      branches: [
        { title: 'Research' },
        { title: 'Ideation' },
        { title: 'Prototyping' },
        { title: 'Testing' },
        { title: 'Launch' },
        { title: 'Growth' },
      ],
    },
  },
  {
    type: 'brain4',
    label: 'brain4',
    description: 'Structure en arbre hiérarchique descendant.',
    category: 'Brains',
    supportsStroke: false,
    defaultData: {
      type: 'brain',
      centerLabel: 'Root Idea',
      branches: [
        { title: 'Strategy', subtitle: 'Level 1' },
        { title: 'Tactics', subtitle: 'Level 2' },
        { title: 'Operations', subtitle: 'Level 2' },
        { title: 'People', subtitle: 'Level 3' },
        { title: 'Process', subtitle: 'Level 3' },
        { title: 'Technology', subtitle: 'Level 3' },
      ],
    },
  },
  {
    type: 'budget',
    label: 'budget',
    description: 'Synthèse du budget total et répartition par postes de dépense.',
    category: 'Budgets',
    defaultData: {
      type: 'budget',
      totalLabel: 'Total Budget',
      totalAmount: '$500K',
      items: [
        { label: 'Engineering', amount: '$200K', percentage: 40, color: '#4a90d9' },
        { label: 'Marketing', amount: '$150K', percentage: 30, color: '#e91e63' },
        { label: 'Operations', amount: '$100K', percentage: 20, color: '#4caf50' },
        { label: 'Admin', amount: '$50K', percentage: 10, color: '#ff9800' },
      ],
    },
  },
  {
    type: 'budget2',
    label: 'budget2',
    description: 'Barres horizontales de répartition du budget par poste, proportionnelles au pourcentage.',
    category: 'Budgets',
    defaultData: {
      type: 'budget',
      totalLabel: 'Total',
      totalAmount: '$1.2M',
      items: [
        { label: 'Engineering', amount: '$400K', percentage: 33 },
        { label: 'Marketing', amount: '$300K', percentage: 25 },
        { label: 'Operations', amount: '$250K', percentage: 21 },
        { label: 'Sales', amount: '$150K', percentage: 12 },
        { label: 'Admin', amount: '$100K', percentage: 8 },
      ],
    },
  },
  {
    type: 'budget3',
    label: 'budget3',
    description: 'Diagramme en anneau (Donut) avec total au centre.',
    category: 'Budgets',
    defaultData: {
      type: 'budget',
      totalLabel: 'Total Budget',
      totalAmount: '$800K',
      items: [
        { label: 'Engineering', amount: '$300K', percentage: 38, color: '#4a90d9' },
        { label: 'Marketing', amount: '$200K', percentage: 25, color: '#e91e63' },
        { label: 'Ops', amount: '$180K', percentage: 22, color: '#4caf50' },
        { label: 'Admin', amount: '$120K', percentage: 15, color: '#ff9800' },
      ],
    },
  },
  {
    type: 'budget4',
    label: 'budget4',
    description: 'Diagramme de cascade (Waterfall) d\'évolution budgétaire.',
    category: 'Budgets',
    defaultData: {
      type: 'budget',
      totalLabel: 'Net',
      totalAmount: '$350K',
      items: [
        { label: 'Revenue', amount: '+$500K', percentage: 100, color: '#2ecc71' },
        { label: 'COGS', amount: '-$150K', percentage: -30, color: '#e74c3c' },
        { label: 'Marketing', amount: '-$80K', percentage: -16, color: '#e74c3c' },
        { label: 'Operations', amount: '-$60K', percentage: -12, color: '#e74c3c' },
        { label: 'R&D', amount: '+$140K', percentage: 28, color: '#2ecc71' },
      ],
    },
  },
  {
    type: 'budget5',
    label: 'budget5',
    description: 'Diagramme circulaire (Pie Chart) des dépenses.',
    category: 'Budgets',
    defaultData: {
      type: 'budget',
      totalLabel: 'Total',
      totalAmount: '$500K',
      items: [
        { label: 'Engineering', amount: '$200K', percentage: 40, color: '#4a90d9' },
        { label: 'Marketing', amount: '$150K', percentage: 30, color: '#e91e63' },
        { label: 'Operations', amount: '$100K', percentage: 20, color: '#4caf50' },
        { label: 'Admin', amount: '$50K', percentage: 10, color: '#ff9800' },
      ],
    },
  },
  {
    type: 'business',
    label: 'business',
    description: 'Sujet central entouré de ses composants business.',
    category: 'Business',
    defaultData: {
      type: 'business',
      centerLabel: 'Core',
      nodes: [
        { title: 'Strategy', subtitle: 'Long-term vision' },
        { title: 'Finance', subtitle: 'Budget & ROI' },
        { title: 'Product', subtitle: 'Development' },
        { title: 'Sales', subtitle: 'Revenue' },
        { title: 'Support', subtitle: 'Customer care' },
        { title: 'HR', subtitle: 'Talent & culture' },
      ],
    },
  },
  {
    type: 'business2',
    label: 'business2',
    description: 'Hub vertical connectant les différents pôles de l\'entreprise.',
    category: 'Business',
    defaultData: {
      type: 'business2',
      centerLabel: 'Strategy',
      nodes: [
        { title: 'Finance', subtitle: 'Budget & ROI' },
        { title: 'Product', subtitle: 'Development' },
        { title: 'Sales', subtitle: 'Revenue' },
        { title: 'Support', subtitle: 'Customer care' },
        { title: 'HR', subtitle: 'Talent & culture' },
        { title: 'Marketing', subtitle: 'Brand growth' },
      ],
    },
  },
  {
    type: 'business3',
    label: 'business3',
    description: 'Grille 2x3 d\'analyse stratégique et opérationnelle.',
    category: 'Business',
    defaultData: {
      type: 'business',
      centerLabel: 'Matrix',
      nodes: [
        { title: 'Strategy', subtitle: 'Vision' },
        { title: 'Finance', subtitle: 'Budget' },
        { title: 'Product', subtitle: 'Dev' },
        { title: 'Sales', subtitle: 'Revenue' },
        { title: 'Support', subtitle: 'Care' },
        { title: 'HR', subtitle: 'Talent' },
      ],
    },
  },
  {
    type: 'business4',
    label: 'business4',
    description: 'Chaîne de valeur représentée par des chevrons successifs.',
    category: 'Business',
    defaultData: {
      type: 'business',
      centerLabel: 'Flow',
      nodes: [
        { title: 'Research', subtitle: 'Discover' },
        { title: 'Design', subtitle: 'Ideate' },
        { title: 'Develop', subtitle: 'Build' },
        { title: 'Test', subtitle: 'Validate' },
        { title: 'Launch', subtitle: 'Ship' },
      ],
    },
  },
  {
    type: 'business5',
    label: 'business5',
    description: 'Disposition en losange des flux d\'interaction d\'affaires.',
    category: 'Business',
    defaultData: {
      type: 'business',
      centerLabel: 'Structure',
      nodes: [
        { title: 'CEO', subtitle: 'Leadership' },
        { title: 'Engineering', subtitle: 'Team A' },
        { title: 'Design', subtitle: 'Team B' },
        { title: 'Results', subtitle: 'Outcome' },
      ],
    },
  },
  {
    type: 'business6',
    label: 'business6',
    description: 'Barres empilées représentant les facteurs d\'affaires.',
    category: 'Business',
    defaultData: {
      type: 'business',
      centerLabel: 'Bars',
      nodes: [
        { title: 'Inbound Logistics' },
        { title: 'Operations' },
        { title: 'Outbound Logistics' },
        { title: 'Marketing & Sales' },
        { title: 'Service' },
        { title: 'Infrastructure' },
      ],
    },
  },
  {
    type: 'business7',
    label: 'business7',
    description: 'Schéma circulaire du cycle de vie des affaires.',
    category: 'Business',
    defaultData: {
      type: 'business',
      centerLabel: 'Core',
      nodes: [
        { title: 'Strategy', subtitle: 'Vision' },
        { title: 'Finance', subtitle: 'Budget' },
        { title: 'Product', subtitle: 'Dev' },
        { title: 'Sales', subtitle: 'Revenue' },
        { title: 'Support', subtitle: 'Care' },
        { title: 'HR', subtitle: 'Talent' },
        { title: 'Marketing', subtitle: 'Brand' },
        { title: 'Legal', subtitle: 'Compliance' },
      ],
    },
  },
  {
    type: 'business8',
    label: 'business8',
    description: 'Liste verticale des fonctions business clés.',
    category: 'Business',
    defaultData: {
      type: 'business',
      centerLabel: 'List',
      nodes: [
        { title: 'Define Vision & Mission' },
        { title: 'Market Research & Analysis' },
        { title: 'Product Development' },
        { title: 'Go-to-Market Strategy' },
        { title: 'Launch & Iterate' },
        { title: 'Scale & Optimize' },
      ],
    },
  },
  {
    type: 'business9',
    label: 'business9',
    description: 'Matrice 3x3 pour le diagnostic d\'entreprise.',
    category: 'Business',
    defaultData: {
      type: 'business',
      centerLabel: 'Grid',
      nodes: [
        { title: 'Strategy' },
        { title: 'Finance' },
        { title: 'Product' },
        { title: 'Sales' },
        { title: 'Support' },
        { title: 'HR' },
        { title: 'Marketing' },
        { title: 'Legal' },
        { title: 'R&D' },
      ],
    },
  },
  {
    type: 'business10',
    label: 'business10',
    description: 'Pyramide à niveaux de la création de valeur.',
    category: 'Business',
    defaultData: {
      type: 'business',
      centerLabel: 'Pyramid',
      nodes: [
        { title: 'CEO Vision', subtitle: 'Leadership' },
        { title: 'VPs', subtitle: 'Management' },
        { title: 'Directors', subtitle: 'Management' },
        { title: 'Managers', subtitle: 'Operations' },
        { title: 'Team Leads', subtitle: 'Operations' },
        { title: 'Engineers', subtitle: 'Operations' },
        { title: 'Analysts', subtitle: 'Foundation' },
        { title: 'Interns', subtitle: 'Foundation' },
        { title: 'Ops', subtitle: 'Foundation' },
        { title: 'Support', subtitle: 'Foundation' },
      ],
    },
  },
  {
    type: 'business11',
    label: 'business11',
    description: 'Timeline de l\'historique et des jalons de la société.',
    category: 'Business',
    defaultData: {
      type: 'business',
      centerLabel: 'Timeline',
      nodes: [
        { title: 'Discovery', subtitle: 'Phase 1' },
        { title: 'Planning', subtitle: 'Phase 2' },
        { title: 'Development', subtitle: 'Phase 3' },
        { title: 'Testing', subtitle: 'Phase 4' },
        { title: 'Launch', subtitle: 'Phase 5' },
        { title: 'Growth', subtitle: 'Phase 6' },
      ],
    },
  },
  {
    type: 'decisionTree',
    label: 'decisionTree',
    description: 'Arbre binaire de choix avec réponses Oui / Non.',
    category: 'Decision trees',
    defaultData: {
      type: 'decisionTree',
      rootQuestion: 'Start project?',
      branches: [
        {
          label: 'Budget OK?',
          answer: 'yes',
          children: [
            { label: 'Resources?', answer: 'yes', outcome: 'Launch' },
            { label: 'Resources?', answer: 'no', outcome: 'Hire first' },
          ],
        },
        { label: 'Budget OK?', answer: 'no', outcome: 'Postpone' },
      ],
    },
  },
  {
    type: 'decision2',
    label: 'decision2',
    description: 'Arbre de décision déployé horizontalement de gauche à droite.',
    category: 'Decision trees',
    defaultData: {
      type: 'decisionTree',
      rootQuestion: 'Launch Product?',
      branches: [
        { label: 'Market ready?', answer: 'yes', children: [
          { label: 'Budget OK?', answer: 'yes', outcome: 'Launch Now' },
          { label: 'Budget OK?', answer: 'no', outcome: 'Seek Funding' },
        ]},
        { label: 'Market ready?', answer: 'no', outcome: 'Wait & Refine' },
      ],
    },
  },
  {
    type: 'goals',
    label: 'goals',
    description: 'Trajectoire ascendante jalonnée vers une cible bicolore.',
    category: 'Goals',
    defaultData: {
      type: 'goals',
      centerGoal: 'Vision 2026',
      metrics: [
        { label: 'Your title 01', value: 'MIGSO-PCUBED content and words to be added here as required', color: '#2c2b64' },
        { label: 'Your title 02', value: 'MIGSO-PCUBED content and words to be added here as required', color: '#2563eb' },
        { label: 'Your title 03', value: 'MIGSO-PCUBED content and words to be added here as required', color: '#ea580c' },
        { label: 'Your title 04', value: 'MIGSO-PCUBED content and words to be added here as required', color: '#eab308' },
      ],
    },
  },
  {
    type: 'goals2',
    label: 'goals2',
    description: 'Cible centrale bicolore avec flèches rayonnantes et empennages colorés.',
    category: 'Goals',
    defaultData: {
      type: 'goals',
      centerGoal: 'Target 2026',
      metrics: [
        { label: 'Your title', value: 'MIGSO-PCUBED content and words to be added here as required', color: '#2c2b64' },
        { label: 'Your title', value: 'MIGSO-PCUBED content and words to be added here as required', color: '#2563eb' },
        { label: 'Your title', value: 'MIGSO-PCUBED content and words to be added here as required', color: '#ea580c' },
        { label: 'Your title', value: 'MIGSO-PCUBED content and words to be added here as required', color: '#eab308' },
        { label: 'Your title', value: 'MIGSO-PCUBED content and words to be added here as required', color: '#10b981' },
      ],
    },
  },
  {
    type: 'goals3',
    label: 'goals3',
    description: 'Cible bicolore avec flèches horizontales et plumes d\'impact.',
    category: 'Goals',
    defaultData: {
      type: 'goals',
      centerGoal: 'KPIs 2026',
      metrics: [
        { label: 'Your title', value: 'MIGSO-PCUBED content and words to be added here as required', color: '#2c2b64' },
        { label: 'Your title', value: 'MIGSO-PCUBED content and words to be added here as required', color: '#2563eb' },
        { label: 'Your title', value: 'MIGSO-PCUBED content and words to be added here as required', color: '#ea580c' },
        { label: 'Your title', value: 'MIGSO-PCUBED content and words to be added here as required', color: '#eab308' },
      ],
    },
  },
  {
    type: 'goals4',
    label: 'goals4',
    description: 'Cible centrale avec couronne segmentée, fléchettes 3D et badges.',
    category: 'Goals',
    defaultData: {
      type: 'goals',
      centerGoal: 'Progress',
      metrics: [
        { label: 'Your title', value: 'MIGSO-PCUBED content and words to be added here as required', color: '#ea580c' },
        { label: 'Your title', value: 'MIGSO-PCUBED content and words to be added here as required', color: '#2c2b64' },
        { label: 'Your title', value: 'MIGSO-PCUBED content and words to be added here as required', color: '#eab308' },
        { label: 'Your title', value: 'MIGSO-PCUBED content and words to be added here as required', color: '#2563eb' },
      ],
    },
  },
  {
    type: 'manufacturing',
    label: 'manufacturing',
    description: 'Ligne de fabrication avec stations et points de contrôle qualité.',
    category: 'Manufacturing',
    defaultData: {
      type: 'manufacturing',
      stations: [
        { title: 'Raw Materials', subtitle: 'Input' },
        { title: 'Processing', subtitle: 'Transform' },
        { title: 'Quality Control', subtitle: 'Verify', isQuality: true },
        { title: 'Assembly', subtitle: 'Build' },
        { title: 'Shipping', subtitle: 'Output' },
      ],
    },
  },
  {
    type: 'valueChain',
    label: 'valueChain',
    description: 'Chaîne de valeur avec activités principales et de soutien.',
    category: 'Value Chain',
    defaultData: {
      type: 'valueChain',
      primary: [
        { title: 'Inbound', subtitle: 'Logistics' },
        { title: 'Operations', subtitle: 'Production' },
        { title: 'Outbound', subtitle: 'Delivery' },
        { title: 'Sales', subtitle: 'Revenue' },
        { title: 'Service', subtitle: 'Support' },
      ],
      support: [
        { title: 'Infrastructure', subtitle: 'IT & Systems' },
        { title: 'HR', subtitle: 'Talent' },
        { title: 'R&D', subtitle: 'Innovation' },
        { title: 'Procurement', subtitle: 'Sourcing' },
      ],
    } as ValueChainData,
  },
  {
    type: 'productRoadmap7',
    label: 'productRoadmap7',
    category: 'Product Roadmaps',
    defaultData: {
      type: 'productRoadmap',
      quarters: [
        { label: 'Q1', year: '2026' },
        { label: 'Q2', year: '2026' },
        { label: 'Q3', year: '2026' },
        { label: 'Q4', year: '2026' },
      ],
      lanes: [],
      milestones: [
        { title: 'Alpha', subtitle: 'Internal testing', quarter: 'Q1' },
        { title: 'Beta', subtitle: 'Private preview', quarter: 'Q2' },
        { title: 'RC1', subtitle: 'Stabilization', quarter: 'Q3' },
        { title: 'GA', subtitle: 'General availability', quarter: 'Q4' },
      ],
    } as ProductRoadmapData,
  },
  {
    type: 'productRoadmap8',
    label: 'productRoadmap8',
    description: 'Calendrier de livraison avec suivi par équipe.',
    category: 'Product Roadmaps',
    defaultData: {
      type: 'productRoadmap',
      quarters: [
        { label: 'Q1', year: '2026' },
        { label: 'Q2', year: '2026' },
        { label: 'Q3', year: '2026' },
        { label: 'Q4', year: '2026' },
      ],
      lanes: [
        { label: 'Engineering' },
        { label: 'Design' },
        { label: 'QA' },
      ],
      milestones: [
        { title: 'Core API', quarter: 'Q1', lane: 'Engineering' },
        { title: 'Wireframes', quarter: 'Q1', lane: 'Design' },
        { title: 'Integration', quarter: 'Q2', lane: 'Engineering' },
        { title: 'Testing', quarter: 'Q3', lane: 'QA' },
        { title: 'Release', quarter: 'Q4', lane: 'Engineering' },
      ],
    } as ProductRoadmapData,
  },
  {
    type: 'productRoadmap9',
    label: 'productRoadmap9',
    description: 'Feuille de route avec barres d\'avancement par trimestre.',
    category: 'Product Roadmaps',
    defaultData: {
      type: 'productRoadmap',
      quarters: [
        { label: 'Q1', year: '2026' },
        { label: 'Q2', year: '2026' },
        { label: 'Q3', year: '2026' },
        { label: 'Q4', year: '2026' },
      ],
      lanes: [],
      milestones: [
        { title: 'Discovery', subtitle: 'Research & ideation', quarter: 'Q1' },
        { title: 'MVP Build', subtitle: 'Core features', quarter: 'Q2' },
        { title: 'Testing', subtitle: 'User validation', quarter: 'Q3' },
        { title: 'Launch', subtitle: 'Go to market', quarter: 'Q4' },
      ],
    } as ProductRoadmapData,
  },
  {
    type: 'productRoadmap10',
    label: 'productRoadmap10',
    description: 'Représentation style Gantt simplifiée pour les livrables produit.',
    category: 'Product Roadmaps',
    defaultData: {
      type: 'productRoadmap',
      quarters: [
        { label: 'Q1', year: '2026' },
        { label: 'Q2', year: '2026' },
        { label: 'Q3', year: '2026' },
        { label: 'Q4', year: '2026' },
      ],
      lanes: [
        { label: 'Frontend' },
        { label: 'Backend' },
        { label: 'DevOps' },
      ],
      milestones: [
        { title: 'Dashboard', quarter: 'Q1', lane: 'Frontend' },
        { title: 'API v1', quarter: 'Q2', lane: 'Backend' },
        { title: 'CI/CD', quarter: 'Q1', lane: 'DevOps' },
        { title: 'Auth', quarter: 'Q3', lane: 'Backend' },
        { title: 'Monitoring', quarter: 'Q4', lane: 'DevOps' },
      ],
    } as ProductRoadmapData,
  },
  {
    type: 'productRoadmap11',
    label: 'productRoadmap11',
    description: 'Affichage par cartes indépendantes dans chaque trimestre.',
    category: 'Product Roadmaps',
    defaultData: {
      type: 'productRoadmap',
      quarters: [],
      lanes: [],
      milestones: [
        { title: 'Discovery', subtitle: 'Understanding user needs and market gaps' },
        { title: 'Prototyping', subtitle: 'Building rapid prototypes for feedback' },
        { title: 'Development', subtitle: 'Engineering the core product modules' },
        { title: 'Integration', subtitle: 'Connecting all components together' },
        { title: 'Release', subtitle: 'Production deployment and monitoring' },
      ],
    } as ProductRoadmapData,
  },
  {
    type: 'productRoadmap12',
    label: 'productRoadmap12',
    description: 'Badges colorés de jalons organisés par trimestre.',
    category: 'Product Roadmaps',
    defaultData: {
      type: 'productRoadmap',
      quarters: [
        { label: 'Q1', year: '2026' },
        { label: 'Q2', year: '2026' },
        { label: 'Q3', year: '2026' },
        { label: 'Q4', year: '2026' },
      ],
      lanes: [],
      milestones: [
        { title: 'Alpha', quarter: 'Q1' },
        { title: 'Beta', quarter: 'Q2' },
        { title: 'RC1', quarter: 'Q3' },
        { title: 'GA', quarter: 'Q4' },
      ],
    } as ProductRoadmapData,
  },
  {
    type: 'strategy6',
    label: 'strategy6',
    description: 'Matrice 2x2 avec axes X et Y paramétrables.',
    category: 'Strategy',
    defaultData: {
      type: 'strategy6',
      axisX: 'Market Growth',
      axisY: 'Competitive Position',
      quadrants: [
        { title: 'Stars', subtitle: 'High growth, strong position', color: '#e3f2fd' },
        { title: 'Question Marks', subtitle: 'High growth, weak position', color: '#fff3e0' },
        { title: 'Cash Cows', subtitle: 'Low growth, strong position', color: '#e8f5e9' },
        { title: 'Dogs', subtitle: 'Low growth, weak position', color: '#fce4ec' },
      ],
    } as Strategy6Data,
  },
  {
    type: 'strategy7',
    label: 'strategy7',
    description: 'Cercles imbriqués illustrant les niveaux d\'impact stratégique.',
    category: 'Strategy',
    defaultData: {
      type: 'strategy',
      blocks: [
        { number: '01', title: 'Long-term Vision', subtitle: '5-year horizon' },
        { number: '02', title: 'Market Leadership', subtitle: 'Global expansion' },
        { number: '03', title: 'Product Strategy', subtitle: 'Platform approach' },
        { number: '04', title: 'Go-to-Market', subtitle: 'Channel partnerships' },
        { number: '05', title: 'Sprint Planning', subtitle: '2-week cycles' },
        { number: '06', title: 'Daily Ops', subtitle: 'Standups & KPIs' },
      ],
    } as StrategyData,
  },
  {
    type: 'strategy8',
    label: 'strategy8',
    description: 'Disposition en escalier illustrant la montée en puissance stratégique.',
    category: 'Strategy',
    defaultData: {
      type: 'strategy',
      blocks: [
        { number: '01', title: 'Foundation', subtitle: 'Build core capabilities' },
        { number: '02', title: 'Growth', subtitle: 'Scale operations' },
        { number: '03', title: 'Optimization', subtitle: 'Efficiency & automation' },
        { number: '04', title: 'Expansion', subtitle: 'New markets & products' },
        { number: '05', title: 'Leadership', subtitle: 'Industry dominance' },
      ],
    } as StrategyData,
  },
  {
    type: 'process1',
    label: 'process1',
    description: 'Schéma minimaliste à 4 étapes avec connecteurs.',
    category: 'Process',
    defaultData: {
      type: 'process',
      title: 'Process 1',
      steps: [
        { number: 1, title: 'Analyze', subtitle: 'Understand the problem' },
        { number: 2, title: 'Design', subtitle: 'Create solution' },
        { number: 3, title: 'Implement', subtitle: 'Build the solution' },
        { number: 4, title: 'Validate', subtitle: 'Test and verify' },
        { number: 5, title: 'Deploy', subtitle: 'Go live' },
      ],
      outcome: 'Success',
    } as ProcessData,
  },
  {
    type: 'table2',
    label: 'table2',
    description: 'Tableau avec lignes bicolores pour une meilleure lisibilité.',
    category: 'Tables',
    defaultData: {
      type: 'table',
      columns: ['Revenue', 'Cost', 'Profit', 'Margin'],
      rows: [
        { label: 'Product A', cells: ['$500K', '$300K', '$200K', '40%'] },
        { label: 'Product B', cells: ['$350K', '$180K', '$170K', '49%'] },
        { label: 'Product C', cells: ['$220K', '$150K', '$70K', '32%'] },
      ],
    } as TableData,
  },
  {
    type: 'table3',
    label: 'table3',
    category: 'Tables',
    defaultData: {
      type: 'table',
      columns: ['Status', 'Owner', 'Deadline'],
      rows: [
        { label: 'Login Page', cells: ['Done', 'Alice', 'Mar 15'] },
        { label: 'Tableau KPI 4 Cartes Métriques',
    description: 'Grille de 4 cartes métriques (Chiffre d\'affaires, Utilisateurs, Churn, NPS).', cells: ['In Progress', 'Bob', 'Mar 30'] },
        { label: 'API Layer', cells: ['Pending', 'Charlie', 'Apr 10'] },
        { label: 'Database', cells: ['Done', 'Diana', 'Mar 20'] },
      ],
    } as TableData,
  },
  {
    type: 'table4',
    label: 'table4',
    description: 'Tableau avec en-tête coloré mis en valeur.',
    category: 'Tables',
    defaultData: {
      type: 'table',
      columns: ['KPI', 'Current', 'Target', 'Status'],
      rows: [
        { label: 'Revenue', cells: ['$2.4M', '$3M', 'On Track'] },
        { label: 'Users', cells: ['48K', '60K', 'Behind'] },
        { label: 'NPS', cells: ['72', '80', 'On Track'] },
        { label: 'Churn', cells: ['2.1%', '1.5%', 'At Risk'] },
      ],
    } as TableData,
  },
  {
    type: 'table5',
    label: 'table5',
    description: 'Design minimaliste sans lignes de séparation.',
    category: 'Tables',
    defaultData: {
      type: 'table',
      columns: ['Q1', 'Q2', 'Q3', 'Q4'],
      rows: [
        { label: 'Revenue', cells: ['$1.2M', '$1.5M', '$1.8M', '$2.1M'] },
        { label: 'Expenses', cells: ['$0.8M', '$1.0M', '$1.2M', '$1.4M'] },
        { label: 'Profit', cells: ['$0.4M', '$0.5M', '$0.6M', '$0.7M'] },
      ],
    } as TableData,
  },
  {
    type: 'table6',
    label: 'table6',
    description: 'Tableau stylisé aux tons bleus professionnels.',
    category: 'Tables',
    defaultData: {
      type: 'table',
      columns: ['Metric', 'Value', 'Change', 'Trend'],
      rows: [
        { label: 'Sessions', cells: ['245K', '+12%', 'Up'] },
        { label: 'Conversions', cells: ['8.4K', '+5%', 'Up'] },
        { label: 'Bounce', cells: ['32%', '-3%', 'Down'] },
        { label: 'Revenue', cells: ['$890K', '+18%', 'Up'] },
      ],
    } as TableData,
  },
  {
    type: 'agenda2',
    label: 'agenda2',
    description: 'Timeline horizontale des créneaux de la réunion.',
    category: 'Agendas',
    defaultData: {
      type: 'agenda',
      items: [
        { number: '01', title: 'Introduction', subtitle: '10 min' },
        { number: '02', title: 'Review', subtitle: '20 min' },
        { number: '03', title: 'Discussion', subtitle: '15 min' },
        { number: '04', title: 'Next Steps', subtitle: '10 min' },
      ],
    } as AgendaData,
  },
  {
    type: 'agenda3',
    label: 'agenda3',
    description: 'Grille horaire par blocs d\'interventions.',
    category: 'Agendas',
    defaultData: {
      type: 'agenda',
      items: [
        { number: '01', title: 'Strategy Review', subtitle: 'Q3 results & Q4 planning' },
        { number: '02', title: 'Product Demo', subtitle: 'New feature showcase' },
        { number: '03', title: 'Team Updates', subtitle: 'Department highlights' },
        { number: '04', title: 'Wrap-up', subtitle: 'Action items & deadlines' },
      ],
    } as AgendaData,
  },
  {
    type: 'agenda4',
    label: 'agenda4',
    description: 'Cartes indépendantes pour chaque sujet de l\'ordre du jour.',
    category: 'Agendas',
    defaultData: {
      type: 'agenda',
      items: [
        { number: '01', title: 'Welcome & Intro', subtitle: 'Setting the stage' },
        { number: '02', title: 'Project Status', subtitle: 'Current progress review' },
        { number: '03', title: 'Open Discussion', subtitle: 'Q&A and feedback' },
        { number: '04', title: 'Closing', subtitle: 'Next steps & action items' },
      ],
    } as AgendaData,
  },
  {
    type: 'comparison2',
    label: 'comparison2',
    description: 'Comparaison entre 3 marques/options avec badges hexagonaux, séparateurs VS et jauges (Slide 67).',
    category: 'Comparisons',
    defaultData: {
      type: 'comparison2',
      blocks: [
        {
          title: 'Brand 01',
          subtitle: 'MIGSO-PCUBED content and words to\nbe added here as required',
          value: '95%',
          icon: 'leaf',
          color: '#2c2b64',
        },
        {
          title: 'Brand 02',
          subtitle: 'MIGSO-PCUBED content and words to\nbe added here as required',
          value: '65%',
          icon: 'mobile',
          color: '#ff5338',
        },
        {
          title: 'Brand 03',
          subtitle: 'MIGSO-PCUBED content and words to\nbe added here as required',
          value: '25%',
          icon: 'phone',
          color: '#f2cb13',
        },
      ],
    } as Comparison2Data,
  },
  {
    type: 'comparison3',
    label: 'comparison3',
    description: 'Barres de mesure horizontales comparatives.',
    category: 'Comparisons',
    defaultData: {
      type: 'comparison',
      leftTitle: 'Option A',
      rightTitle: 'Option B',
      items: [
        { label: 'Cost', left: '$10K', right: '$15K' },
        { label: 'Time', left: '3 months', right: '6 months' },
        { label: 'Risk', left: 'Low', right: 'Medium' },
        { label: 'ROI', left: 'High', right: 'Medium' },
      ],
    } as ComparisonData,
  },
  {
    type: 'comparison4',
    label: 'comparison4',
    description: 'Comparaison visuelle sous forme de cercles proportionnels.',
    category: 'Comparisons',
    defaultData: {
      type: 'comparison',
      leftTitle: 'Product A',
      rightTitle: 'Product B',
      items: [
        { label: 'Cloud-native', left: '', right: '' },
        { label: 'Auto-scaling', left: '', right: '' },
        { label: '24/7 Support', left: '', right: '' },
        { label: 'On-premise', left: '', right: '' },
        { label: 'Custom SLA', left: '', right: '' },
        { label: 'White-label', left: '', right: '' },
      ],
    } as ComparisonData,
  },
  {
    type: 'comparison5',
    label: 'comparison5',
    description: 'Comparaison côte-à-côte avec chevrons d\'options et colonnes d\'items.',
    category: 'Comparisons',
    defaultData: {
      type: 'comparison5',
      leftOption: 'Option 01',
      rightOption: 'Option 02',
      leftItems: [
        { text: 'MIGSO-PCUBED content and words to be added here as required', icon: 'leaf' },
        { text: 'MIGSO-PCUBED content and words to be added here as required', icon: 'trophy' },
        { text: 'MIGSO-PCUBED content and words to be added here as required', icon: 'award' },
        { text: 'MIGSO-PCUBED content and words to be added here as required', icon: 'target' },
        { text: 'MIGSO-PCUBED content and words to be added here as required', icon: 'star' },
      ],
      rightItems: [
        { text: 'MIGSO-PCUBED content and words to be added here as required', icon: 'leaf' },
        { text: 'MIGSO-PCUBED content and words to be added here as required', icon: 'trophy' },
        { text: 'MIGSO-PCUBED content and words to be added here as required', icon: 'award' },
        { text: 'MIGSO-PCUBED content and words to be added here as required', icon: 'target' },
        { text: 'MIGSO-PCUBED content and words to be added here as required', icon: 'star' },
      ],
    } as Comparison5Data,
  },
  {
    type: 'comparison6',
    label: 'comparison6',
    description: 'Comparaison bidirectionnelle Option 1 vs Option 2 par aspects avec barres de pourcentage horizontales.',
    category: 'Comparisons',
    defaultData: {
      type: 'comparison6',
      leftTitle: 'Option 01',
      leftSubtitle: 'MIGSO-PCUBED content and words to be added here as required',
      rightTitle: 'Option 02',
      rightSubtitle: 'MIGSO-PCUBED content and words to be added here as required',
      aspects: [
        { label: 'Aspect 01', leftPercent: 75, rightPercent: 50 },
        { label: 'Aspect 02', leftPercent: 25, rightPercent: 100 },
        { label: 'Aspect 03', leftPercent: 100, rightPercent: 25 },
        { label: 'Aspect 04', leftPercent: 50, rightPercent: 75 },
      ],
    } as Comparison6Data,
  },
  {
    type: 'comparison7',
    label: 'comparison7',
    description: 'Comparaison PROS vs CONS avec deux hexagones centraux et branches connectées à des listes d\'arguments.',
    category: 'Comparisons',
    defaultData: {
      type: 'comparison7',
      leftTitle: 'PROS',
      rightTitle: 'CONS',
      pros: [
        { title: 'MIGSO-PCUBED content and words to be added here as required' },
        { title: 'MIGSO-PCUBED content and words to be added here as required' },
        { title: 'MIGSO-PCUBED content and words to be added here as required' },
        { title: 'MIGSO-PCUBED content and words to be added here as required' },
        { title: 'MIGSO-PCUBED content and words to be added here as required' },
      ],
      cons: [
        { title: 'MIGSO-PCUBED content and words to be added here as required' },
        { title: 'MIGSO-PCUBED content and words to be added here as required' },
        { title: 'MIGSO-PCUBED content and words to be added here as required' },
        { title: 'MIGSO-PCUBED content and words to be added here as required' },
        { title: 'MIGSO-PCUBED content and words to be added here as required' },
      ],
    } as Comparison7Data,
  },
  {
    type: 'comparison8',
    label: 'comparison8',
    description: 'Tableau 2 colonnes comparant Plan A et Plan B avec calcul dynamique de hauteur de ligne synchronisée.',
    category: 'Comparisons',
    defaultData: {
      type: 'comparison8',
      leftTitle: 'Plan A',
      rightTitle: 'Plan B',
      leftItems: ['Cloud hosting', 'Auto-scaling', 'CDN included', 'SSL cert', 'Daily backups'],
      rightItems: ['On-premise', 'Manual scaling', 'No CDN', 'Own cert', 'Weekly backups'],
    } as Comparison8Data,
  },
  {
    type: 'manufacturing2',
    label: 'manufacturing2',
    description: 'Flux de production vertical de l\'entrée matière au produit fini.',
    category: 'Manufacturing',
    defaultData: {
      type: 'manufacturing',
      stations: [
        { title: 'Raw Materials', subtitle: 'Input reception & sorting' },
        { title: 'Processing', subtitle: 'Transform raw materials' },
        { title: 'Quality Control', subtitle: 'Inspection & testing', isQuality: true },
        { title: 'Assembly', subtitle: 'Build final product' },
        { title: 'Shipping', subtitle: 'Package & deliver' },
      ],
    } as ManufacturingData,
  },
  {
    type: 'manufacturing3',
    label: 'manufacturing3',
    description: 'Disposition des postes de travail en forme de U.',
    category: 'Manufacturing',
    defaultData: {
      type: 'manufacturing',
      stations: [
        { title: 'Raw Materials', subtitle: 'Input reception' },
        { title: 'Cutting', subtitle: 'Precision cutting' },
        { title: 'Painting', subtitle: 'Surface treatment' },
        { title: 'Assembly', subtitle: 'Final assembly' },
        { title: 'Packaging', subtitle: 'Ready for dispatch' },
      ],
    } as ManufacturingData,
  },
  {
    type: 'manufacturing4',
    label: 'manufacturing4',
    description: 'Lignes d\'assemblage parallèles convergentes.',
    category: 'Manufacturing',
    defaultData: {
      type: 'manufacturing',
      stations: [
        { title: 'Production A', subtitle: 'Main line' },
        { title: 'Production B', subtitle: 'Main line' },
        { title: 'Production C', subtitle: 'Main line' },
        { title: 'Inspection A', subtitle: 'Quality check', isQuality: true },
        { title: 'Inspection B', subtitle: 'Quality check', isQuality: true },
        { title: 'Inspection C', subtitle: 'Quality check', isQuality: true },
      ],
    } as ManufacturingData,
  },
  {
    type: 'manufacturing5',
    label: 'manufacturing5',
    description: 'Diagramme de processus de fabrication en losange.',
    category: 'Manufacturing',
    defaultData: {
      type: 'manufacturing',
      stations: [
        { title: 'Planning', subtitle: 'Production plan' },
        { title: 'Execution', subtitle: 'Build process' },
        { title: 'Delivery', subtitle: 'Ship to client' },
        { title: 'Feedback', subtitle: 'Client review' },
      ],
    } as ManufacturingData,
  },
  {
    type: 'manufacturing6',
    label: 'manufacturing6',
    description: 'Réseau logistique hub & rayons.',
    category: 'Manufacturing',
    defaultData: {
      type: 'manufacturing',
      stations: [
        { title: 'Supplier A', subtitle: 'Raw materials' },
        { title: 'Supplier B', subtitle: 'Components' },
        { title: 'Supplier C', subtitle: 'Packaging' },
        { title: 'Distributor X', subtitle: 'Region East' },
        { title: 'Distributor Y', subtitle: 'Region West' },
        { title: 'Distributor Z', subtitle: 'Region South' },
      ],
    } as ManufacturingData,
  },
  {
    type: 'manufacturing7',
    label: 'manufacturing7',
    description: 'Calendrier des étapes de fabrication.',
    category: 'Manufacturing',
    defaultData: {
      type: 'manufacturing',
      stations: [
        { title: 'Design', subtitle: 'Blueprint phase' },
        { title: 'Prototype', subtitle: 'Build sample' },
        { title: 'Test', subtitle: 'Validate sample' },
        { title: 'Produce', subtitle: 'Mass production' },
        { title: 'Ship', subtitle: 'Distribute' },
      ],
    } as ManufacturingData,
  },
  {
    type: 'manufacturing8',
    label: 'manufacturing8',
    description: 'Flux de production en boucle fermée (recyclage / réutilisation).',
    category: 'Manufacturing',
    defaultData: {
      type: 'manufacturing',
      stations: [
        { title: 'Input', subtitle: 'Receive' },
        { title: 'Process', subtitle: 'Transform' },
        { title: 'Inspect', subtitle: 'Verify' },
        { title: 'Package', subtitle: 'Prepare' },
        { title: 'Store', subtitle: 'Warehouse' },
        { title: 'Deliver', subtitle: 'Ship' },
      ],
    } as ManufacturingData,
  },
  {
    type: 'valueChain2',
    label: 'valueChain2',
    description: 'Vue verticale des activités principales et de soutien.',
    category: 'Value Chain',
    defaultData: {
      type: 'valueChain',
      primary: [
        { title: 'Inbound', subtitle: 'Logistics' },
        { title: 'Operations', subtitle: 'Production' },
        { title: 'Outbound', subtitle: 'Delivery' },
        { title: 'Sales', subtitle: 'Revenue' },
        { title: 'Service', subtitle: 'Support' },
      ],
      support: [
        { title: 'Infrastructure', subtitle: 'IT & Systems' },
        { title: 'HR', subtitle: 'Talent' },
        { title: 'R&D', subtitle: 'Innovation' },
        { title: 'Procurement', subtitle: 'Sourcing' },
      ],
    } as ValueChainData,
  },
  {
    type: 'valueChain4',
    label: 'valueChain4',
    description: 'Chaîne de valeur inclinée avec Value streams, Supporting activities et flèche centrale.',
    category: 'Value Chain',
    defaultData: {
      type: 'valueChain4',
      upperLabel: 'Value streams',
      lowerLabel: 'Supporting activities',
      centerLabel: 'Reference architecture',
      rightLabel: 'Efficiency\n& Agility',
      primary: [
        { title: 'Strategy to portfolio', subtitle: 'Plan' },
        { title: 'Requirement to deploy', subtitle: 'Build' },
        { title: 'Request to fulfill', subtitle: 'Deliver' },
        { title: 'Detect to correct', subtitle: 'Run' },
      ],
      support: [
        { title: 'Governance risk & compliance' },
        { title: 'Sourcing & vendor' },
        { title: 'Intelligence & reporting' },
        { title: 'Finance & assets' },
        { title: 'Resource & project' },
      ],
    } as ValueChain4Data,
  },
  {
    type: 'valueChain5',
    label: 'valueChain5',
    description: 'Chaîne de valeur avec blocs d’entrée, barres horizontales convergentes et double chevron.',
    category: 'Value Chain',
    defaultData: {
      type: 'valueChain5',
      leftBlocks: [
        { title: 'Your\ntext here' },
        { title: 'Your\ntext here' },
        { title: 'Your\ntext here' },
      ],
      centerBars: [
        { title: 'Your text here' },
        { title: 'Your text here' },
        { title: 'Your text here' },
        { title: 'Your text here' },
        { title: 'Your text here' },
        { title: 'Your text here' },
      ],
      rightChevrons: [
        { title: 'Your text here', subtitle: 'Your text here' },
        { title: 'Your text here', subtitle: 'Your text here' },
      ],
    } as ValueChain5Data,
  },
  {
    type: 'valueChain3',
    label: 'valueChain3',
    description: 'Chaîne de valeur horizontale avec barres supérieure et inférieure et chevrons imbriqués.',
    category: 'Value Chain',
    defaultData: {
      type: 'valueChain3',
      topBar: 'Product Design',
      bottomBar: 'Marketing & Sales',
      footerText: 'MIGSO-PCUBED content and words to be added here as required',
      items: [
        { title: 'Logistics', color: '#1a2249' },
        { title: 'Purchasing', color: '#2b63d9' },
        { title: 'Manufacturing', color: '#ff5338' },
        { title: 'Distribution', color: '#ffb100' },
        { title: 'Service', color: '#48bb95' },
      ],
    } as ValueChain3Data,
  },
  {
    type: 'circle',
    label: 'circle',
    description: 'Cycle itératif en 4 étapes (PDCA / Amélioration continue).',
    category: 'Cycles',
    defaultData: {
      type: 'circle',
      title: 'Circle',
      segments: [
        { number: '01', title: 'Your title 01', description: 'Content and words to be added here as required', icon: '💬' },
        { number: '02', title: 'Your title 02', description: 'Content and words to be added here as required', icon: '' },
        { number: '03', title: 'Your title 03', description: 'Content and words to be added here as required', icon: '💼' },
      ],
    } as CircleData,
  },
  {
    type: 'pieChart1',
    label: 'pieChart1',
    description: 'Donut à 3 parts égales avec marqueurs numérotés et légende.',
    category: 'Pie Charts',
    defaultData: {
      type: 'pieChart1',
      slices: [
        { label: '01', value: 34, color: '#2c2b64' },
        { label: '02', value: 33, color: '#3366cc' },
        { label: '03', value: 33, color: '#ff5338' },
      ],
    } as PieData,
  },
  {
    type: 'pieChart2',
    label: 'pieChart2',
    description: 'Donut avec titre central et libellés autour, 4 parts.',
    category: 'Pie Charts',
    defaultData: {
      type: 'pieChart2',
      title: 'Total',
      slices: [
        { label: 'Libellé 01', value: 25, pct: '25%', color: '#2c2b64' },
        { label: 'Libellé 02', value: 25, pct: '25%', color: '#3366cc' },
        { label: 'Libellé 03', value: 25, pct: '25%', color: '#ff5338' },
        { label: 'Libellé 04', value: 25, pct: '25%', color: '#f2cb13' },
      ],
    } as PieData,
  },
  {
    type: 'pieChart3',
    label: 'pieChart3',
    description: 'Donut à 6 parts numérotées avec légende.',
    category: 'Pie Charts',
    defaultData: {
      type: 'pieChart3',
      slices: [
        { label: '1', value: 17, color: '#2c2b64' },
        { label: '2', value: 17, color: '#3366cc' },
        { label: '3', value: 16, color: '#ff5338' },
        { label: '4', value: 17, color: '#f2cb13' },
        { label: '5', value: 16, color: '#5cc29d' },
        { label: '6', value: 17, color: '#f27798' },
      ],
    } as PieData,
  },
  {
    type: 'pieChart4',
    label: 'pieChart4',
    description: 'Comparaison de 3 mini-donuts à 2 parts avec pourcentages.',
    category: 'Pie Charts',
    defaultData: {
      type: 'pieChart4',
      title: 'Comparaison',
      slices: [
        { label: 'A', value: 90, pct: '90%', color: '#2c2b64' },
        { label: 'B', value: 10, color: '#3366cc' },
        { label: 'A', value: 80, pct: '80%', color: '#ff5338' },
        { label: 'B', value: 20, color: '#f2cb13' },
        { label: 'A', value: 65, pct: '65%', color: '#5cc29d' },
        { label: 'B', value: 35, color: '#f27798' },
      ],
    } as PieData,
  },
  {
    type: 'pieChart5',
    label: 'pieChart5',
    description: 'Camembert à 4 parts pondérées avec libellés et pourcentages.',
    category: 'Pie Charts',
    defaultData: {
      type: 'pieChart5',
      slices: [
        { label: 'Part 01', value: 15, pct: '15%', color: '#2c2b64' },
        { label: 'Part 02', value: 35, pct: '35%', color: '#3366cc' },
        { label: 'Part 03', value: 20, pct: '20%', color: '#ff5338' },
        { label: 'Part 04', value: 30, pct: '30%', color: '#f2cb13' },
      ],
    } as PieData,
  },
]

export function getTemplateByType(type: string): TemplateDefinition | undefined {
  return TEMPLATES.find(t => t.type === type)
}

export function getTemplatesByCategory(): Map<string, TemplateDefinition[]> {
  const map = new Map<string, TemplateDefinition[]>()
  for (const t of TEMPLATES) {
    const list = map.get(t.category) ?? []
    list.push(t)
    map.set(t.category, list)
  }
  return map
}
